version: '3'

services:
  api:
    image: hello
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=turhan99
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
    driver: local

