version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4

    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "443:443"

    volumes:
      - ./config/traefik.yaml:/etc/traefik.yaml
      - ./config/all.yaml:/all.yaml

  whoami:
    # A container that exposes an API to show its IP address
    image: hello
    ports:
      - "8090:8090"



