version: '3'

services:
  reverse-proxy:
    image: traefik:v2.4
    restart: always
    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
      - "443:443"

    volumes:
      - ./configs/traefik.yaml:/traefik.yaml
      - ./configs/all.yaml:/all.yaml
    networks:
      - web

  api:
    image: hello
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - postgresql
    networks:
      - web
      - backend


  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=turhan99
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend


volumes:
  postgres-data:
    driver: local

networks:
  web:
    external: true
  backend:
    external: false