http:
  routers:
    unsecurerouter:
      rule: "Host(`hackrpad.com`)"
      service: allbackend
    allbackendRouter:
      rule: "Host(`hackrpad.com`)"
      service: allbackend
      tls:
        certResolver: myresolver
        options: tlsoptions
    apiRouter:
      rule: "Host(`hackrpad.com`) && PathPrefix(`/api/`)"
      service: apibackend
      tls:
        certResolver: myresolver
        options: tlsoptions

  services:
    allbackend:
      loadBalancer:
        servers:
          - url: "http://hackrpad.com:8090/"
    apibackend:
      loadBalancer:
        servers:
          - url: "http://hackrpad.com:8001/"

tls:
  options:
    tlsoptions:
      minVersion: VersionTLS12
