http:
  routers:
    unsecurerouter:
      rule: "Host(`localhost`)"
      service: allbackend
    allbackendRouter:
      rule: "Host(`localhost`)"
      service: allbackend
      tls:
        certResolver: myresolver
        options: tlsoptions

  services:
    allbackend:
      loadBalancer:
        servers:
          - url: "http://localhost:8090/"

tls:
  options:
    tlsoptions:
      minVersion:  VersionTLS12
