# Static configuration

entryPoints:
  unsecure:
    address: :80
    http:
      redirections:
        entryPoint:
          to: secure
          scheme: https
  secure:
    address: :443

certificatesResolvers:
  myresolver:
    acme:
      email: cureoglu1@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: unsecure
providers:
  file:
    filename: all.yaml
    watch: true

api:
  dashboard: true
  insecure: true