name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  CD:
    name: Continous Delivery
    runs-on: ubuntu-latest
    steps:
      - name: SSH into production server
        uses: appleboy/ssh-action@master
        with:
          host: 167.71.16.181
          username: root
          key: ${{secrets.CD_SK}}
          port: 22
          script: |
            cd tryinghttps
            git pull
            docker image build -t hello .
            docker-compose -f production.yaml down
            docker-compose -d -f production.yaml up
